In [29]:
import numpy as np

In [87]:
a = np.array([[30, 60], [56,23]])
b = np.array([20, 40])

print(a)
print(b)


[[30 60]
 [56 23]]
[20 40]


In [49]:
#adding vectors
print("Sum :", (a + b).T)

#substracting vectors
print("sub: ", (a - b).T)

# scala multiply
c = 2

print("scaler : ", (c * a).T)

print("dot product : ", (a * b).T)


Sum : [[ 50]
 [100]]
sub:  [[10]
 [20]]
scaler :  [[ 60]
 [120]]
dot product :  [[ 600]
 [2400]]


In [89]:
#Dot product of 2 vectors
dot_product = np.dot(a, b)
print("dot_product = ", dot_product)

dot_product =  [3000 2040]


In [93]:
x = np.array([[23,8,9], [4, 78,9], [8,1,0]])
y = np.array([[2,18,90], [47, 8,19], [2,1,30]])
print("x = ", x.T )
print("y = ", y.T)

x =  [[23  4  8]
 [ 8 78  1]
 [ 9  9  0]]
y =  [[ 2 47  2]
 [18  8  1]
 [90 19 30]]


In [85]:
x * y

array([[ 46, 144, 810],
       [188, 624, 171],
       [ 16,   1,   0]])

In [95]:
pwd


'C:\\Users\\Administrator\\Documents\\AI\\uncertainity\\linear-algebra'

In [99]:
ls -l

 Volume in drive C has no label.
 Volume Serial Number is 7CA6-8E5A

 Directory of C:\Users\Administrator\Documents\AI\uncertainity\linear-algebra



File Not Found
